import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import SideBar from "@/components/side-bar";
import Header from "@/components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    template: "%s  | Feedback Product",
    default: "Feedback Product",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${geistSans.variable} ${geistMono.variable} bodycontent` } >
        <SideBar />
        <div >
          <Header />
          {children}
        </div>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
