import { Jost } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "%s  | Feedback Product",
    default: "Feedback Product",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${jost.className} bodycontent`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
