export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function LoginLayout({ children }) {
  return <div className="logincontent">{children}</div>;
}
